name: build multi-arch images

on: {push: {branches: [benleb]}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with: {ref: benleb}
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with: {buildx-version: latest}
      - name: login to docker hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          docker buildx build --push \
            --tag benleb/appdaemon:dev \
            --platform linux/amd64,linux/arm64,linux/arm/v7 .
